### ISSUE TITLE
Quiz mode's strokes behavior is buggy when going fast

### ISSUE THREAD

**Issue by vaab** [chanind/hanzi-writer#43] opened 2018-02-05 09:16 UTC
I noticed that some strokes could then not be rendered with the final color (various shades of gray and not the final black for instance), probably because their opacity animation was stopped before completing (you can experience this on the demo site quite easily).

In some cases they would even stay lingering after end of quiz mode. Note that this might be a second issue. I'm willing to work on that the next days of this week.

**Comment by chanind** [comment] 2018-02-05 16:18
Ack, this looks like another regression from #24. Previously svg.js would force animations to end at their final value if they were canceled early, but that functionality wasn't carried over when replacing the library.

**Comment by chanind** [comment] 2018-02-05 17:17
This may be been fixed by #46, but animations will need a rewrite to make sure they're solid in all situations.

**Comment by chanind** [comment] 2018-02-08 03:05
Closing as this should have been fixed. If it's still occurring we can reopen.

**Closed by chanind** 2018-02-08 03:05 UTC

**Comment by vaab** [comment] 2018-02-09 09:12
I indeed could not reproduce the problem on my end with the same setup. Thanks for the fix.
