### ISSUE TITLE
cancel animation will generate javascript errors

### ISSUE THREAD

**Issue by vaab** [chanind/hanzi-writer#50] opened 2018-02-06 03:53 UTC
There are many different place where the cancelation of animation will trigger javascript exceptions.

For instance, if asking for a forever animated loop for a known caracter then loading an unknown character will trigger issues in ``animateForever()`` on line ``var animatePromise = this._characterRenderer.animate(animation);`` as ``this._characterRenderer`` was removed in ``setCharacter()``.

Note: PR #44 tackles a lot of these issues.

**Comment by chanind** [comment] 2018-02-06 17:29
Ack great catch again! #51 should fix this specific bug with looping and loading a new character, but you're right that this is just a bandaid on the core issue that animations aren't managed well. It wouldn't surprise me if there are more subtle bugs like this hiding with calling `setCharacter()` during animations depending on where in the animation cycle the load occurs. My hope is to take some time this weekend to or early next week to try to think through how to rearchitect how animations are managed so that issues like these become impossible. I think part of the problem is that a lot of the animations currently are chained using normal promises, so we have to keep checking while the animation is running whether everything is still in a sane state. We can't easily cancel a promise chain partway through. It's probably a good idea to research how other libraries handle this too.

**Comment by chanind** [comment] 2018-02-23 01:31
This should be fixed by #56

**Closed by chanind** 2018-02-23 01:31 UTC
Labels: backend
